### ISSUE TITLE
另类数据库更新方法

### ISSUE THREAD

**Issue by Taskeren** [ProjectUranus/destiny-bot-mirai#3]
https://github.com/DeepStoneCrypt/DestinyBotMiraiDataUpdater

不知道对不对，看 Bot 没用到 Activity 就没有搞。
之前听说更新数据库很慢，但是我用这个挺快的。 0w0

**Comment by LasmGratel** [comment]
数据库更新慢主要是因为下载两个130多M的大JSON文件，以及把数据库再传到服务器比较慢。
有时间了我就写一个完整的 Workflow 让 CI 来搞这些东西

________________________________
发件人: 倪钍 ***@***.***>
发送时间: 2021年9月29日星期三 下午10:45
收件人: ProjectUranus/destiny-bot-mirai
抄送: Subscribed
主题: [ProjectUranus/destiny-bot-mirai] 另类数据库更新方法 (#3)


https://github.com/DeepStoneCrypt/DestinyBotMiraiDataUpdater

不知道对不对，看 Bot 没用到 Activity 就没有搞。
之前听说更新数据库很慢，但是我用这个挺快的。 0w0

―

**Comment by Taskeren** [comment]
不过我看bot用不到那么多东西啊，看起来顶多只要 ItemDefinition 和 Activity 就够了的样子

**Comment by LasmGratel** [comment]
嗯确实
实际上我想把整个命运2的东西直接砍掉了
